# Start from a base image with Miniconda installed
FROM continuumio/miniconda3:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the environment file.
# The `.` at the end means "copy the file from the current directory on your machine"
COPY environment_charla.yml .

# Create the Conda environment
RUN conda env create -f environment_charla.yml

# Set up the environment for use
ENV PATH="/opt/conda/envs/charla_nf/bin:$PATH"
